apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeMachine
spec:
  replicas: 1
  selector:
    matchLabels:
      name: timeMachine
  template:
    metadata:
      labels:
        name: timeMachine
    spec:
      serviceAccountName: timeMachine
      containers:
        - name: timeMachine
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "timeMachine"
