apiVersion: apps/v1
kind: Deployment
metadata:
  name: timemachine
spec:
  replicas: 1
  selector:
    matchLabels:
      name: timemachine
  template:
    metadata:
      labels:
        name: timemachine
    spec:
      serviceAccountName: timemachine
      containers:
        - name: timemachine
          # Replace this with the built image name
          image: mcano/timemachine-operator:1.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "timemachine"
