kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: timemachine
subjects:
- kind: ServiceAccount
  name: timemachine
roleRef:
  kind: Role
  name: timemachine
  apiGroup: rbac.authorization.k8s.io
