apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myhelmoperators.helm.operator-sdk
spec:
  group: helm.operator-sdk
  names:
    kind: MyHelmOperator
    listKind: MyHelmOperatorList
    plural: myhelmoperators
    singular: myhelmoperator
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
