apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-operator.fullname" . }}
  labels:
    {{- include "helm-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{default "1.0.0" .Values.timemachine.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JUMP_DATE
              value: {{default "" .Values.timemachine.jump_date }}
            - name: VERSION
              value: {{default "1.0.0" .Values.timemachine.version }}
            - name: FLUX_ENABLED
              value: "{{ .Values.timemachine.flux_enabled }}"
          ports:
            - name: http
              containerPort: {{ default 5000 .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http

