apiVersion: helm.operator-sdk/v1alpha1
kind: TimeMachine
metadata:
  name: timemachine-1955
spec:
  # Default values copied from <project_dir>/helm-charts/my-helm-operator/values.yaml
  image:
    pullPolicy: Always
    repository: mcano/future-is-now
  timemachine:
    flux_enabled: false
    jump_date: November 5, 1955
    version: 1.0.0

  ingress:
    annotations: {}
    enabled: false
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  replicaCount: 2
  service:
    port: 80
    type: LoadBalancer

